### ISSUE TITLE
Specific Classroom bugs

### ISSUE THREAD

**Issue by DavidWigley** [DavidWigley/WITRoomFinder#18]
Some classrooms such as Wentworth 209 do not work under current search algorithm. They are not being indexed properly and as a result it shows this room being open when in reality it is taken.

**Comment by TylerPentecost** [comment]
I think I would like to make an attempt at this.

**Comment by DavidWigley** [comment]
I'll review and test your changes when I have time. Thank you for your attempt :)

**Comment by DavidWigley** [comment]
@Zolerii I reviewed your code and was concerned with one of the conditionals. I made a comment on your commit. I think it would mess up the math you laid out with determining conflicts. Also your way does require a bit of math to be done so for the moment I'm going to stick with my logic.

**Comment by DavidWigley** [comment]
Wentworth 209 actually just has 2 classes in it during the week. I think its used as like a conference room or something? I'm not really sure. I just combed through the course registration data manually and could only find 2 classes using this room. 

Going to close this issue.
