### ISSUE TITLE
Display Issue

### ISSUE THREAD

**Issue by DavidWigley** [DavidWigley/WITRoomFinder#33]
Classrooms overlap the banner at the top.

**Comment by DavidWigley** [comment]
Could be android versions. Greg is on a newer one than I am so maybe we have some conditional that if they're on new they get the nicer stuff from greg and if they are on the old they get my display.

**Comment by edhall111** [comment]
Yeah greg is alot better than you actually I concur

**Comment by DavidWigley** [comment]
Resolved in most recent merge.
